#!/bin/bash

# Program finished

trap 'echo "Program finished";exit' 0 1 2 15

# Ensure we have the quantity specified on the CLI
if [ -z "$2" ]; then ARG_ERR=ERR; fi
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: <delayinseconds> <command>"
    exit 1
fi

# Ensure the command exists
if ! "$2" 2>/dev/null >/dev/null
then
    echo "$2 -> Command not found"
    exit 2
fi

delay=$1
commandtorun=$2

while true;
  do $commandtorun
  sleep $delay
done

# The same thing can be written as a one-liner
# while true; do echo ./genoutput && sleep 15; done
