#!/bin/sh

# The histappend command is generally configured on zsh when setting up
# and it needs to be placed in your ~/.bashrc when running this script.
#  shopt -s histappend
#  export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

#Ensure we have the quantity specified on the CLI
if [ -z "$2" ]; then ARG_ERR=ERR; fi
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: <sleeptimesecs> <numberoflines>"
    exit
fi

sleeptimesecs=$1
numberoflines=$2

# Tail history
while [ 1 ]; do
	clear
    tail -$numberoflines ~/.bash_history
    sleep $sleeptimesecs
done
