#!/bin/sh

#Ensure we have the quantity specified on the CLI
if [ -z "$2" ]; then ARG_ERR=ERR; fi
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: <sleeptimesecs> <numberoflines>"
    exit
fi

sleeptimesecs=$1
numberoflines=$2

# Tail history
while [ 1 ]; do
	clear
    tail -$numberoflines ~/.zsh_history | sed s/^...............//
    sleep $sleeptimesecs
done
