#!/bin/sh

#Ensure we have the quantity specified on the CLI
if [ -z "$2" ]; then ARG_ERR=ERR; fi
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: <sleeptimesecs> <commandtorun>"
    exit
fi

sleeptimesecs=$1
commandtorun=$2

while [ 1 ]; do
	clear
    $commandtorun
    sleep $sleeptimesecs
done
