#!/bin/sh

# Convert OrgMode to Markdown
export MARKDOWNNAME="`echo "$1" | sed 's/$/.markdown/'`"
export HTMLNAME="`echo "$1" | sed 's/$/.html/'`"

# Syntax of OrgMode
# * for first level bullet -> H1
# ** for second level bullet -> first level markdown bullet
# == for codeblock becomes `


#| tr -d '^   :[:alpha:]:$'  \
#| tr -d '^   :[:alpha:]:[:blank:][:alnum:]$'  \

# Convert OrgMode to Markdown
cat "$1" \
         | sed "s/   :PROPERTIES://"  \
         | sed "s/   :Effort:.*//"  \
         | sed "s/   :END://"  \
         | sed "s/ ==/\`/"  \
         | sed "s/== /\`/"  \
         | sed "s/^\* /# /"  \
         | sed "s/^\*\* /## /"  \
         | sed "s/^\*\*\* /\* /" \
         | sed "s/^\*\*\*\* /    \* /" \
         | sed "s/^\*\*\*\*\* /        \* /" > "$MARKDOWNNAME"

# Convert from Markdown to HTML
cat "$MARKDOWNNAME" | multimarkdown > "$HTMLNAME"
