#!/bin/bash

#Ensure we have the quantity specified on the CLI
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: treelive <depth>"
    echo "Usage: treelive <depth> <OTHERTREEARGS>"
    exit
fi

DEPTH=$1

while :
do
    clear
    tree -L $*
    sleep 2
done
