#!/bin/bash
osascript -e 'tell application "Mail" to quit'
sleep 1
before=`ls -lah ~/Library/Mail/V2/MailData | grep -E 'Envelope Index$' | awk {'print $5'}`

# do the vacuum
/usr/bin/sqlite3 ~/Library/Mail/V2/MailData/Envelope\ Index vacuum
after=`ls -lah ~/Library/Mail/V2/MailData | grep -E 'Envelope Index$' | awk {'print $5'}`
echo "Mail index before: $before"
echo "Mail index after: $after"
echo "Enjoy the new speed!"

osascript -e 'tell application "Mail" to activate'
sleep 1
osascript -e 'tell application "System Events" to set visible of application process "Mail" to false'
